// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCylf6ho-JxzneX1vF13s7Cwt_ZoTDOEhk',
    appId: '1:459429596882:web:c833ea62a2b35cb03fa70b',
    messagingSenderId: '459429596882',
    projectId: 't-store-app-20f8f',
    authDomain: 't-store-app-20f8f.firebaseapp.com',
    storageBucket: 't-store-app-20f8f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZPoVnO8UN4B0n9T5-3_juZG043AnQ8jc',
    appId: '1:459429596882:android:b40e2df42fe72cc33fa70b',
    messagingSenderId: '459429596882',
    projectId: 't-store-app-20f8f',
    storageBucket: 't-store-app-20f8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMywbQSTorU-Q4Hu2KJq1IEOIQK9WYrb4',
    appId: '1:459429596882:ios:dd2eca7df90ba41b3fa70b',
    messagingSenderId: '459429596882',
    projectId: 't-store-app-20f8f',
    storageBucket: 't-store-app-20f8f.appspot.com',
    androidClientId: '459429596882-20kviiqb8oivq7u5475kkimfp8d8r1l1.apps.googleusercontent.com',
    iosClientId: '459429596882-ja14llfo3d24r9h035gpg0org17eu5i3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}